"""Genera catalogo.yaml y descarga los SVG de Lucide (versión fijada). Ejecutar una vez."""
import subprocess, yaml
from pathlib import Path

VERSION = "1.48.0"
# icono lucide: (etiquetas en español, sonido semántico)
ICONOS = {
 "rocket": ("cohete, despegar, lanzar, otro nivel, crecer rápido, escalar", "despegue"),
 "trash-2": ("basura, tirar, papelera, eliminar, desperdiciar, borrar", "papel"),
 "file-text": ("documento, archivo, plan, texto, informe", "papel"),
 "files": ("archivos, documentos, muchos archivos", "papel"),
 "folder": ("carpeta, proyecto, archivos", "click"),
 "folder-open": ("abrir proyecto, carpeta abierta", "click"),
 "map": ("mapa, plano, estructura, orientarse", "transformacion"),
 "map-pin": ("ubicación, lugar, dónde está", "pop"),
 "compass": ("brújula, dirección, rumbo, estrategia", "transformacion"),
 "network": ("red, conexiones, nodos, integraciones", "red"),
 "share-2": ("compartir, conectar, distribuir", "red"),
 "link": ("enlace, conectar, link, vincular", "click"),
 "plug": ("conectar, integración, enchufar", "click"),
 "puzzle": ("complemento, plugin, pieza, extensión, encajar", "pop"),
 "server": ("servidor, proveedores, infraestructura, nube", "red"),
 "cloud": ("nube, online, cloud", "red"),
 "database": ("base de datos, datos, información", "red"),
 "cpu": ("procesador, computación, potencia", "red"),
 "bot": ("robot, bot, agente, IA, asistente, automatizar", "transformacion"),
 "brain": ("cerebro, inteligencia, pensar, IA, aprender", "transformacion"),
 "sparkles": ("magia, IA, brillo, mejorar, nuevo", "transformacion"),
 "wand-sparkles": ("varita, magia, transformar, automático", "transformacion"),
 "zap": ("rayo, rápido, energía, instantáneo, potencia", "subida"),
 "terminal": ("terminal, consola, comandos, código, Claude Code", "teclado"),
 "code": ("código, programar, desarrollo", "teclado"),
 "code-xml": ("código, html, desarrollo web", "teclado"),
 "keyboard": ("teclado, escribir, teclear", "teclado"),
 "laptop": ("portátil, ordenador, trabajar online", "click"),
 "monitor": ("pantalla, ordenador, escritorio", "click"),
 "smartphone": ("móvil, teléfono, app, celular", "mensaje"),
 "app-window": ("aplicación, ventana, software, app", "pop"),
 "layout-dashboard": ("panel, dashboard, métricas, control", "pop"),
 "settings": ("ajustes, configuración, engranaje, sistema", "engranaje"),
 "workflow": ("flujo, proceso, sistema, automatización", "engranaje"),
 "repeat": ("repetir, una y otra vez, bucle, recurrente", "click"),
 "refresh-cw": ("actualizar, cambiar, rotar, renovar", "engranaje"),
 "search": ("buscar, revisar, investigar, encontrar", "click"),
 "scan-search": ("escanear, analizar, revisar", "click"),
 "eye": ("ver, mirar, visibilidad, atención", "pop"),
 "dollar-sign": ("dinero, dólares, precio, cobrar", "moneda"),
 "circle-dollar-sign": ("dinero, ingresos, beneficio, pagar", "moneda"),
 "coins": ("monedas, dinero, ahorro, gastar, tokens", "moneda"),
 "banknote": ("billete, dinero, efectivo, pago", "moneda"),
 "wallet": ("cartera, dinero, gastar, bolsillo", "moneda"),
 "piggy-bank": ("ahorro, hucha, ahorrar dinero", "moneda"),
 "credit-card": ("tarjeta, pago, suscripción, cobro", "moneda"),
 "hand-coins": ("pagar, cobrar, vender, ganar dinero", "moneda"),
 "receipt": ("factura, recibo, cobro", "papel"),
 "calculator": ("calculadora, cálculo, números, cuentas", "click"),
 "percent": ("porcentaje, descuento, tasa", "pop"),
 "trending-up": ("crecer, subir, aumentar, mejorar, ganar", "subida"),
 "trending-down": ("bajar, caer, perder, disminuir, menos", "bajada"),
 "chart-line": ("gráfico, evolución, tendencia, resultados", "subida"),
 "chart-column": ("barras, estadística, comparar datos", "subida"),
 "chart-pie": ("porcentaje, reparto, cuota", "pop"),
 "target": ("objetivo, meta, precisión, cliente ideal", "pop"),
 "trophy": ("ganar, éxito, logro, premio, mejor", "ding"),
 "crown": ("rey, líder, el mejor, premium", "ding"),
 "medal": ("medalla, logro, reconocimiento", "ding"),
 "star": ("estrella, destacado, favorito, calidad", "ding"),
 "badge-check": ("verificado, garantizado, oficial", "ding"),
 "circle-check": ("correcto, hecho, listo, sí", "ding"),
 "list-checks": ("lista, tareas, checklist, pasos", "click"),
 "clipboard-list": ("tareas, pendientes, organizar", "click"),
 "circle-x": ("error, no, incorrecto, fallo", "alerta"),
 "triangle-alert": ("alerta, peligro, cuidado, riesgo, advertencia", "alerta"),
 "ban": ("prohibido, nunca, no hagas, evitar", "alerta"),
 "bug": ("bug, error, fallo técnico", "alerta"),
 "skull": ("peligro, muerte, fracaso, fatal", "alerta"),
 "flame": ("fuego, tendencia, quemar, caliente, viral", "subida"),
 "lock": ("seguridad, candado, privado, bloquear", "candado"),
 "lock-open": ("desbloquear, acceso, abrir", "candado"),
 "shield-check": ("seguro, protección, confianza", "candado"),
 "key-round": ("llave, acceso, clave, secreto", "candado"),
 "fingerprint": ("identidad, huella, único", "candado"),
 "clock": ("tiempo, reloj, horas, rápido, tarde", "reloj"),
 "timer": ("temporizador, minutos, rapidez, cronómetro", "reloj"),
 "hourglass": ("reloj de arena, esperar, tiempo perdido", "reloj"),
 "calendar": ("calendario, fecha, días, mes, agenda", "click"),
 "alarm-clock": ("alarma, urgente, despertar, fecha límite", "reloj"),
 "user": ("persona, usuario, tú, cliente, una persona", "pop"),
 "users": ("personas, equipo, clientes, gente, comunidad", "pop"),
 "user-plus": ("nuevo cliente, seguidor, sumar persona", "pop"),
 "user-check": ("cliente, usuario verificado", "ding"),
 "briefcase": ("trabajo, negocio, empresa, profesional", "click"),
 "building-2": ("empresa, oficina, corporación, Wall Street", "pop"),
 "landmark": ("banco, institución, gobierno, bolsa", "pop"),
 "store": ("tienda, negocio, comercio", "pop"),
 "shopping-cart": ("comprar, venta, carrito, ecommerce", "moneda"),
 "package": ("producto, paquete, envío, pack", "pop"),
 "gift": ("regalo, gratis, bonus, regalar", "ding"),
 "handshake": ("acuerdo, trato, cliente, colaborar", "pop"),
 "megaphone": ("anunciar, marketing, publicidad, difundir", "pop"),
 "message-circle": ("mensaje, chat, comentar, conversación", "mensaje"),
 "message-square-text": ("mensaje, comentario, texto, escribir", "mensaje"),
 "send": ("enviar, mandar, link, compartir", "mensaje"),
 "mail": ("email, correo, newsletter", "mensaje"),
 "bell": ("notificación, aviso, alerta", "mensaje"),
 "phone": ("llamada, teléfono, llamar", "mensaje"),
 "globe": ("mundo, global, internet, internacional", "red"),
 "earth": ("planeta, mundo entero, global", "red"),
 "lightbulb": ("idea, bombilla, ocurrencia, solución", "pop"),
 "book-open": ("libro, aprender, curso, guía", "papel"),
 "graduation-cap": ("aprender, curso, formación, master class", "ding"),
 "pencil": ("escribir, editar, lápiz", "teclado"),
 "pen-tool": ("diseño, crear, dibujar", "transformacion"),
 "image": ("imagen, foto, visual", "camara"),
 "camera": ("cámara, foto, grabar", "camara"),
 "video": ("vídeo, grabar, contenido, reel", "camara"),
 "mic": ("micrófono, hablar, podcast, voz", "pop"),
 "play": ("reproducir, empezar, vídeo, play", "click"),
 "layers": ("capas, niveles, pila, estructura", "transformacion"),
 "boxes": ("cajas, módulos, piezas, componentes", "pop"),
 "gauge": ("rendimiento, velocidad, medidor", "subida"),
 "battery-charging": ("cargar, energía, recargar", "subida"),
 "battery-low": ("sin batería, agotado, sin energía, quedarse sin", "bajada"),
 "infinity": ("infinito, ilimitado, sin límite", "transformacion"),
 "shuffle": ("mezclar, cambiar, alternar, aleatorio", "click"),
 "split": ("dividir, separar, bifurcar", "click"),
 "merge": ("unir, fusionar, juntar", "click"),
 "arrow-right-left": ("intercambiar, cambiar, de un lado a otro", "click"),
 "move-up-right": ("subir, avanzar, progreso", "subida"),
 "scale": ("comparar, equilibrio, justicia, balanza", "pop"),
 "magnet": ("atraer, imán, captar clientes", "pop"),
 "sprout": ("crecer, empezar, semilla, orgánico", "subida"),
 "mountain": ("montaña, reto, cima, meta", "subida"),
 "house": ("casa, vivienda, hogar, piso, inmueble", "pop"),
 "key": ("llave, piso, propiedad, acceso", "candado"),
 "hammer": ("construir, arreglar, herramienta", "click"),
 "wrench": ("herramienta, arreglar, ajustar", "engranaje"),
 "party-popper": ("celebrar, fiesta, éxito, lanzamiento", "ding"),
 "smile": ("feliz, sonrisa, satisfecho", "pop"),
 "frown": ("triste, problema, frustración", "bajada"),
 "heart": ("amor, me gusta, favorito", "pop"),
 "thumbs-up": ("bien, aprobar, recomendar, like", "pop"),
 "thumbs-down": ("mal, no recomendar, dislike", "bajada"),
 "flag": ("bandera, meta, objetivo, hito", "pop"),
 "bookmark": ("guardar, marcador, guárdalo", "click"),
}
base = Path(__file__).parent
(base / "svg").mkdir(exist_ok=True)
ok, fallan = {}, []
for nombre, (etiquetas, sonido) in ICONOS.items():
    destino = base / "svg" / f"{nombre}.svg"
    if not destino.exists():
        r = subprocess.run(["curl", "-sfL", "-o", str(destino), f"https://unpkg.com/lucide-static@{VERSION}/icons/{nombre}.svg"])
        if r.returncode != 0:
            fallan.append(nombre); destino.unlink(missing_ok=True); continue
    ok[nombre] = {"etiquetas": [e.strip() for e in etiquetas.split(",")], "sonido": sonido}
(base / "catalogo.yaml").write_text("# Iconos Lucide v" + VERSION + " (licencia ISC, ver LICENSE). Generado por catalogo_fuente.py\n"
    + yaml.safe_dump({"iconos": ok}, allow_unicode=True, sort_keys=False, width=200), encoding="utf-8")
print(len(ok), "iconos;", "no existen:", fallan)
